"""add status to screenshots

Revision ID: 3bc3cbf38170
Revises: 24fa22826d7d
Create Date: 2026-04-07 01:44:51.657286

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3bc3cbf38170"
down_revision: Union[str, Sequence[str], None] = "24fa22826d7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        "CREATE TYPE screenshotstatus AS ENUM ('processing', 'completed', 'failed')"
    )
    op.add_column(
        "screenshots",
        sa.Column(
            "status",
            sa.Enum("processing", "completed", "failed", name="screenshotstatus"),
            nullable=False,
            server_default="processing",
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("screenshots", "status")
    # ### end Alembic commands ###
